name: Build Proton-TKG with dx12fix Patch

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo lib32-jack2 git vulkan-headers linux-api-headers

      - name: Create User
        run: |
          useradd -m -G wheel -s /bin/bash user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Clone Proton-TKG and Apply patches
        run: |
          git clone https://github.com/Frogging-Family/wine-tkg-git.git
          cp patches/dx12fix.patch wine-tkg-git

          cd wine-tkg-git
          git apply dx12fix.patch

          chown user -R ..
          chown user -R /tmp
          export CARGO_HOME="$PWD"
          cd proton-tkg
          
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          sed -i 's/LOCAL_PRESET=\"\"/LOCAL_PRESET=\"none\"/' proton-tkg.cfg
          sed -i 's/_no_container="true"/_no_container="false"/' proton-tkg.sh
          echo '_ci_build="true"' >> proton-tkg.cfg

          echo "cat proton-tkg.sh"
          cat proton-tkg.sh

      - name: Compile Proton-TKG
        run: |
          cd wine-tkg-git/proton-tkg
          touch tarplz
          yes | ./proton-tkg.sh

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: wine-tkg-git/proton-tkg/built/*.tar
